### PR TITLE
Passthrough vendored feature flag

### PR DESCRIPTION
**Pull request by ShayBox**
Passthrough vendored feature flag to allow installing via `cargo install --git URL --features vendored`

### CODE REVIEW

**Comment by mhils** [comment]
Could you clarify what the use case is here? WinDivert is LGPL, so I don't want to link it statically in any way.

**Comment by ShayBox** [comment]
The vendored feature flag on windivert/windivert-sys just uses the upstream git repo as the source directory for compiling bindings instead of the user manually downloading the source code zip and setting up a WINDIVERT_PATH env, it doesn't statically link and still requires the binary be run with the officially signed dynamic driver files.

This just makes it easier to initially install the package using `cargo install` without setting up the aforementioned WINDIVERT_PATH.

**Comment by mhils** [comment]
Ah thanks - I was mixing up `vendored` and `static`. 

What are you trying to do that you need to set `WINDIVERT_PATH`? `mitmproxy_rs` copies over the libraries and should "just work". Are you attempting to use `windows-redirector` without mitmproxy? How are you providing the .sys file in vendored mode? I'm not opposed to the change here, I'm just trying to understand it. :)

**Comment by ShayBox** [comment]
I couldn't find anything about how to use windows-redirector and I don't see anything in windows-redirector that should be fetching the source before compilation

I just installed mitmproxy using winget and windows-redirector using `cargo install --git URL windows-redirector` but it failed to compile windivert-sys because I didn't have a folder containing the windivert source and env, I don't see anything in the build scripts that are supposed to download and extract the source but maybe I missed it, or I'm using this the wrong way

After installing with my fork I was able to download and extract the signed driver files into a folder, cd into it, and run windows-redirector within that cwd from the cargo global bin, without having to setup the whole mitmproxy_rs repo and `cargo build -p windows-redirector` a binary

**Comment by mhils** [comment]
What is the high-level goal you are trying to accomplish? Simply use mitmproxy with the new Windows redirector, or something else?

**Comment by ShayBox** [comment]
Yeah I'm just trying to use it with mitmproxy

**Comment by mhils** [comment]
Well great, that makes things easier. 😃 The new Windows redirector is still unreleased work-in-progress, which is why there is no documentation yet and no obvious way to use it. We're getting there in the coming months though! :) 

For now: The simplest way to try out the new OS proxy mode is grab snapshot binaries from CI: https://github.com/mitmproxy/mitmproxy/actions/workflows/main.yml?query=branch%3Amain+event%3Apush
and then run something like `mitmproxy --mode osproxy:curl.exe`. You don't need to install anything beyond (a still unreleased version of) mitmproxy. Apart from that, feedback is welcome and testing is appreciated! 😃

**Comment by ShayBox** [comment]
Oh that makes things much easier, it even comes as an installer 😄 thanks

**Comment by mhils** [comment]
Excellent, thanks! 😃

**Pull request closed without merging**
