### PR TITLE
Windows: Add `process_list()`

### PR DESCRIPTION
**Pull request by mhils**

### CODE REVIEW

**Comment by meitinger** [comment]
Some comments on the icon extraction:
There is a way to get the icon data (PNG or BMP) from a process (module in general) without going through GDI. And, if we're only dealing with path to executables, `ExtractAssociatedIcon` is overkill (as we don't want to lookup shell icons in the registry). Plus using this API also loses different icon sizes.

Since the goal is to view the icon in mitmweb anyway, it might actually be best to extract the whole icon with all sizes. All modern browsers support `.ico`, and in a way this makes having a `srcset` obsolete.

Here's the sample Rust code to extract the primary icon of an `.exe` to a vector and a file:
(Sorry for the absolut beginner lever Rust code in advance 😅)

```rust
use bytestream::*;
use std::{ffi::c_void, fs::File, io::Write};
use windows::{
    core::{HSTRING, PCWSTR},
    Win32::Foundation::{BOOL, HANDLE, HMODULE},
    Win32::{
        Foundation::ERROR_RESOURCE_ENUM_USER_STOP,
        System::LibraryLoader::{
            EnumResourceNamesW, FindResourceW, FreeLibrary, LoadLibraryExW, LoadResource,
            LockResource, LOAD_LIBRARY_AS_DATAFILE,
        },
    },
};

// describes an entry in an icon group
#[repr(packed)]
struct GRPICONDIRENTRY {
    width: u8,
    height: u8,
    color_count: u8,
    reserved: u8,
    planes: u16,
    bit_count: u16,
    bytes_in_res: u32,
    id: u16, // on file, this is a u32 offset to the actual data (BMP or PNG)
}

// describes an icon group
#[repr(packed)]
struct GRPICONDIR {
    reserved: u16,
    dir_type: u16,
    count: u16,
    entries: [GRPICONDIRENTRY; 0],
}

// missing defines and macros
const RT_ICON: PCWSTR = PCWSTR(3 as *const u16);
const RT_GROUP_ICON: PCWSTR = PCWSTR((3 + 11) as *const u16);

fn is_int_resource(lpname: PCWSTR) -> bool {
    lpname.0 <= (0xFFFF as *const u16)
}

// helper for pretty printing
unsafe fn res_name_to_str(lpname: PCWSTR) -> String {
    if is_int_resource(lpname) {
        format!("#{}", lpname.0 as isize)
    } else {
        match lpname.to_string() {
            Ok(str) => str,
            Err(_) => format!("{lpname:?}"),
        }
    }
}

// helper that will be called for each icon group and icon item
unsafe fn find_load_and_lock_resource(
    hmodule: HMODULE,
    lpname: PCWSTR,
    lptype: PCWSTR,
) -> windows::core::Result<*mut c_void> {
    let hresinfo = FindResourceW(hmodule, lpname, lptype);
    if hresinfo.is_invalid() {
        Err(windows::core::Error::from_win32())
    } else {
        let mem = LockResource(LoadResource(hmodule, hresinfo)?);
        if mem.is_null() {
            Err(windows::core::Error::from_win32())
        } else {
            Ok(mem)
        }
    }
}

fn write_u8<W: Write>(buffer: &mut W, value: u8) -> std::io::Result<()> {
    value.write_to(buffer, ByteOrder::LittleEndian)
}

fn write_u16<W: Write>(buffer: &mut W, value: u16) -> std::io::Result<()> {
    value.write_to(buffer, ByteOrder::LittleEndian)
}

fn write_u32<W: Write>(buffer: &mut W, value: u32) -> std::io::Result<()> {
    value.write_to(buffer, ByteOrder::LittleEndian)
}

unsafe fn write_icon<W: Write>(
    hmodule: HMODULE,
    lpname: PCWSTR,
    buffer: &mut W,
) -> std::io::Result<()> {
    let name = res_name_to_str(lpname);

    // get the icon directory
    match find_load_and_lock_resource(hmodule, lpname, RT_GROUP_ICON) {
        Ok(group_ptr) => {
            let group = &*(group_ptr as *const GRPICONDIR);
            let count = group.count as usize;
            let entries = std::slice::from_raw_parts(group.entries.as_ptr(), count);
            println!("primary icon group {name} containing {count} entries");

            // write the directory header
            write_u16(buffer, group.reserved)?;
            write_u16(buffer, group.dir_type)?;

            // get each icon entry
            let mut items = Vec::<(&GRPICONDIRENTRY, *const u8)>::with_capacity(count);
            for i in 0..count {
                let entry = &entries[i];
                let id = entry.id;
                match find_load_and_lock_resource(hmodule, PCWSTR(id as *const u16), RT_ICON) {
                    Ok(item) => {
                        items.push((entry, item as *const u8));
                        println!(
                            "  {i}: icon #{}, {}x{}, {}bpp",
                            entry.id as u16,
                            if entry.width == 0 {
                                256
                            } else {
                                entry.width as u16
                            },
                            if entry.height == 0 {
                                256
                            } else {
                                entry.height as u16
                            },
                            entry.bit_count as u16,
                        );
                    }
                    Err(e) => println!("  {i}: failed to get icon #{id} data: {e:?}"),
                }
            }

            // complete the directory
            let mut offset =
                2 /*reserved*/+ 2 /*type*/ + 2 /*count*/ + 16 /*ICONDIRENTRY*/ * items.len();
            write_u16(buffer, items.len() as u16)?;
            for (entry, _) in &items {
                write_u8(buffer, entry.width)?;
                write_u8(buffer, entry.height)?;
                write_u8(buffer, entry.color_count)?;
                write_u8(buffer, entry.reserved)?;
                write_u16(buffer, entry.planes)?;
                write_u16(buffer, entry.bit_count)?;
                write_u32(buffer, entry.bytes_in_res)?;
                write_u32(buffer, offset as u32)?;
                offset = offset + entry.bytes_in_res as usize;
            }

            // write the data
            // the data is either a PNG or BMP without a header (since the header is in the item entry)
            for (entry, data) in &items {
                buffer.write_all(std::slice::from_raw_parts(
                    *data,
                    entry.bytes_in_res as usize,
                ))?;
            }
        }
        Err(e) => println!("failed to get icon group {name}: {e:?}"),
    }
    Ok(())
}

unsafe fn save_icon(hmodule: HMODULE, lpname: PCWSTR, path: &String) -> std::io::Result<()> {
    // create the output file
    let mut file = File::create(path)?;
    let mut buffer = Vec::<u8>::new();
    write_icon(hmodule, lpname, &mut buffer)?;
    file.write_all(&buffer)?;
    Ok(())
}

// callback for EnumResourceNamesW
unsafe extern "system" fn enum_icon_group_names(
    hmodule: HMODULE,
    _lptype: PCWSTR,
    lpname: PCWSTR,
    _lparam: isize,
) -> BOOL {
    // save the primary icon and stop enumerating
    let path = std::env::args().nth(2).expect("no output icon path given");
    match save_icon(hmodule, lpname, &path) {
        Ok(()) => println!("icon file {path} saved"),
        Err(e) => println!("failed to save icon file {path}: {e:?}"),
    }
    return BOOL(0);
}

fn main() {
    let module_name = &HSTRING::from(std::env::args().nth(1).expect("no input module name given"));
    unsafe {
        // load the module as data file (faster, more secure for DLLs)
        match LoadLibraryExW(module_name, HANDLE(0), LOAD_LIBRARY_AS_DATAFILE) {
            Ok(module) => {
                // enum all icon groups (the callback will stop after the first one)
                match EnumResourceNamesW(module, RT_GROUP_ICON, Some(enum_icon_group_names), 0).ok()
                {
                    Ok(()) => {} // fishy, we expect ERROR_RESOURCE_ENUM_USER_STOP
                    Err(e) => {
                        if e.code() != ERROR_RESOURCE_ENUM_USER_STOP.to_hresult() {
                            println!("failed to enum icon groups: {e:?}");
                        }
                    }
                }
                FreeLibrary(module);
            }
            Err(e) => println!("error loading library: {e:?}"),
        }
    }
}
```

**Comment by mhils** [comment]
@meitinger: super neat, thanks! 🍰 

> And, if we're only dealing with path to executables, ExtractAssociatedIcon is overkill (as we don't want to lookup shell icons in the registry). 

I super vaguely recall that ExtractIcon was not good enough, although I may be hallucinating here? I need to check how your approach performs with my process list. IIRC, one benfit of ExtractAssociatedIcon was that I get fallback "default executable" images, but that would be tolerable.

> Plus using this API might also lose different icon sizes.

It definitely does. I've basically deemed whatever is returned as "good enough", we don't want to display them super big anyways. With ICO we should take a quick look whether that produces wild outliers in file size, but I'd be cautiously optimistic.


Completely separate from your efforts I've spent some time today to do additional benchmarking and optimization. There now is a cache for getting icons and display names, performance now is a non-issue (no matter which approach we pick). 😃

**Comment by meitinger** [comment]
> With ICO we should take a quick look whether that produces wild outliers in file size, but I'd be cautiously optimistic.

I've run the program on all `.exe` in my `%windir%\system32`, the biggest outlier was a 550 KB icon from `LPlatSvc.exe` (Lenovo seem to like their app icons really shiny^^). The average `.ico` size of all 189 executables (with icon) is 57.8 KB.

Plus the source is written in a way that is very easy to filter out bigger icons, just cap on `bytes_in_res`.

> I super vaguely recall that ExtractIcon was not good enough, although I may be hallucinating here?

`ExtractIcon` only handles modules and `ico` files. `ExtractAssociatedIcon` can basically be used in shell views and on all file types, and will most likely also return the default executable icon if an `.exe` has no `RT_ICON_GROUP` resource. However, you can use my code to extract icon group #⁠15 from `%windir%\system32\imageres.dll`, which will give you that icon (or icon group #⁠3 from `shell32.exe`, if XP is still a thing _somewhere_ :)

**Comment by meitinger** [comment]
Besides icons: If you're interested, I could write some code using `EnumServicesStatusEx` to correlate service names with process ids. Especially for `svchost.exe` we could then use a more meaningful display name. For `rundll32.exe` we could do something similar and use the `FileDescription` of the DLL it was launched with.

**Pull request merged**
